# Generated by Django 3.0.5 on 2020-04-07 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuetype",
            name="name",
            field=models.TextField(
                max_length=256, unique=True, verbose_name="Issue Type Name"
            ),
        ),
        migrations.CreateModel(
            name="IssueSubType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        max_length=256, unique=True, verbose_name="Issue Sub Type Name"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_issue_type",
                        to="issues.IssueType",
                    ),
                ),
            ],
        ),
    ]
