# Generated by Django 3.0.5 on 2020-04-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_issue_owner"),
    ]

    operations = [
        migrations.RemoveField(model_name="issue", name="created_by",),
        migrations.AddField(
            model_name="issue",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name="issue",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
    ]
