# Generated by Django 3.0.5 on 2020-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0003_auto_20200410_0215"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                default="medium",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("fraud", "Fraud"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="issue",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
