# Generated by Django 3.0.5 on 2020-04-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_auto_20200410_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('fraud', 'Fraud')], default='', max_length=100),
        ),
    ]
